name: dart_playpoker
version: 0.2.6
author: Claudio d'Angelis
description: A simplified version of Poker game written in Dart.
homepage: http://www.claudiodangelis.it/projects/dart-playpoker
dependencies:
  browser: any
