name: dart-playpoker
version: 0.2.1
description: A simplified of the Poker game written in Dart.
author: Claudio Dawson d'Angelis @daw___
homepage: http://www.claudiodangelis.it/projects/dart-playpoker